# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help_ui(object):
    def setupUi(self, help_ui):
        help_ui.setObjectName("help_ui")
        help_ui.resize(782, 706)
        help_ui.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.close_btn = QtWidgets.QPushButton(help_ui)
        self.close_btn.setGeometry(QtCore.QRect(690, 660, 75, 23))
        self.close_btn.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.close_btn.setObjectName("close_btn")
        self.textBrowser = QtWidgets.QTextBrowser(help_ui)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 781, 421))
        self.textBrowser.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(help_ui)
        QtCore.QMetaObject.connectSlotsByName(help_ui)

    def retranslateUi(self, help_ui):
        _translate = QtCore.QCoreApplication.translate
        help_ui.setWindowTitle(_translate("help_ui", "Form"))
        self.close_btn.setText(_translate("help_ui", "закрыть"))
        self.textBrowser.setHtml(_translate("help_ui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Вас приветствует команда разработки данного приложения по обработке файлов Excel из отдела Нормативно Справочной Информации</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1) Первым шагом необходимо выбрать файл, который будет обрабатываться. Для этого необходимо нажать на кнопку Открыть</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2) После этого необходимо выбрать нужные параметры:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.1) Выбрать нужные поля из списка доступных ключей, по которым будет происходить отбор, можно с помощью кнопки &gt;. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Выбранные ключи будут отображаться в списке справа. Для удаления ключа необходимо нажать кнопку &lt;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.2) В выпадающем списке снизу, можно выбрать ...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.3) В поле выбора цветов можно выбрать цвета нажав на соотвествующее поле</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.4) В поле выбора методов обработки, необходимо выбрать один из метод обработки файла</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">... БУДЕТ ДОПОЛНЕНО ...</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    help_ui = QtWidgets.QWidget()
    ui = Ui_help_ui()
    ui.setupUi(help_ui)
    help_ui.show()
    sys.exit(app.exec_())
