# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 721)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_file.setGeometry(QtCore.QRect(20, 140, 111, 23))
        self.button_open_file.setAutoFillBackground(False)
        self.button_open_file.setStyleSheet("\n"
"QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }\n"
"")
        self.button_open_file.setCheckable(False)
        self.button_open_file.setChecked(False)
        self.button_open_file.setAutoRepeatDelay(300)
        self.button_open_file.setObjectName("button_open_file")
        self.label_file_name = QtWidgets.QLabel(self.centralwidget)
        self.label_file_name.setGeometry(QtCore.QRect(160, 140, 461, 21))
        self.label_file_name.setObjectName("label_file_name")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(200, 310, 25, 23))
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add.setObjectName("pushButton_add")
        self.list_keys = QtWidgets.QListWidget(self.centralwidget)
        self.list_keys.setGeometry(QtCore.QRect(10, 220, 180, 192))
        self.list_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}")
        self.list_keys.setObjectName("list_keys")
        self.list_selected_keys = QtWidgets.QListWidget(self.centralwidget)
        self.list_selected_keys.setGeometry(QtCore.QRect(240, 220, 180, 192))
        self.list_selected_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys.setObjectName("list_selected_keys")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(200, 260, 25, 23))
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.result_button = QtWidgets.QPushButton(self.centralwidget)
        self.result_button.setGeometry(QtCore.QRect(560, 580, 151, 23))
        self.result_button.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.result_button.setObjectName("result_button")
        self.print_complited = QtWidgets.QLabel(self.centralwidget)
        self.print_complited.setGeometry(QtCore.QRect(460, 580, 91, 16))
        self.print_complited.setText("")
        self.print_complited.setObjectName("print_complited")
        self.keys_label = QtWidgets.QLabel(self.centralwidget)
        self.keys_label.setGeometry(QtCore.QRect(10, 190, 180, 21))
        self.keys_label.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label.setObjectName("keys_label")
        self.keys_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.keys_label_2.setGeometry(QtCore.QRect(240, 190, 180, 21))
        self.keys_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_2.setObjectName("keys_label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 620, 741, 23))
        self.progressBar.setStyleSheet("color: rgb(42, 138, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 20, 201, 101))
        self.logo.setStyleSheet("image: url(:/newPrefix/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.mbu_fk = QtWidgets.QLabel(self.centralwidget)
        self.mbu_fk.setGeometry(QtCore.QRect(240, 30, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mbu_fk.setFont(font)
        self.mbu_fk.setObjectName("mbu_fk")
        self.mbu_fk_2 = QtWidgets.QLabel(self.centralwidget)
        self.mbu_fk_2.setGeometry(QtCore.QRect(240, 70, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.mbu_fk_2.setFont(font)
        self.mbu_fk_2.setObjectName("mbu_fk_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 430, 271, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(440, 210, 111, 201))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: -24px;\n"
"  padding-left: 8px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.checkBox_red = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_red.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_red.setObjectName("checkBox_red")
        self.checkBox_green = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_green.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.checkBox_green.setObjectName("checkBox_green")
        self.checkBox_blue = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_blue.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.checkBox_blue.setObjectName("checkBox_blue")
        self.checkBox_yellow = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_yellow.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.checkBox_yellow.setObjectName("checkBox_yellow")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 210, 181, 201))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: -24px;\n"
"  padding-left: 8px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 161, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 161, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 60, 161, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.help_button = QtWidgets.QPushButton(self.centralwidget)
        self.help_button.setGeometry(QtCore.QRect(620, 30, 75, 23))
        self.help_button.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.help_button.setObjectName("help_button")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(10, 650, 211, 31))
        self.version.setObjectName("version")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_open_file.setText(_translate("MainWindow", "открыть файл"))
        self.label_file_name.setText(_translate("MainWindow", "File name"))
        self.pushButton_add.setText(_translate("MainWindow", ">"))
        self.pushButton_delete.setText(_translate("MainWindow", "<"))
        self.result_button.setText(_translate("MainWindow", "Результат"))
        self.keys_label.setText(_translate("MainWindow", "Список ключей"))
        self.keys_label_2.setText(_translate("MainWindow", "Список выбранных ключей"))
        self.mbu_fk.setText(_translate("MainWindow", "Межрегиональное Бухгалтерское"))
        self.mbu_fk_2.setText(_translate("MainWindow", "УФК"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Только уникальные (по заполнености)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Только уникальные (по выделеному столбцу)"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Только повторы"))
        self.groupBox.setTitle(_translate("MainWindow", "выбор цвета"))
        self.checkBox_red.setText(_translate("MainWindow", "red"))
        self.checkBox_green.setText(_translate("MainWindow", "green"))
        self.checkBox_blue.setText(_translate("MainWindow", "blue"))
        self.checkBox_yellow.setText(_translate("MainWindow", "yellow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "выбор варианта обработки"))
        self.radioButton.setText(_translate("MainWindow", "вариант обработки 1"))
        self.radioButton_2.setText(_translate("MainWindow", "вариант обработки 2"))
        self.radioButton_3.setText(_translate("MainWindow", "вариант обработки 3"))
        self.help_button.setText(_translate("MainWindow", "Помощь"))
        self.version.setText(_translate("MainWindow", "ver. 0.4"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
